### ISSUE TITLE
add screendump

### ISSUE THREAD

**Issue by sander76** [andrey-git/home-assistant-custom-ui#1]
Just a small remark.
Would be great if you could add a screenshot of the custom ui you created...

Sander.

**Comment by andrey-git** [comment]
Added screenshots to README

![wide](https://cloud.githubusercontent.com/assets/5478779/23335593/e344048e-fbc0-11e6-81fd-85466a6b98b2.png)

![medium](https://cloud.githubusercontent.com/assets/5478779/23335594/e909eee2-fbc0-11e6-8429-8648b89d6d13.png)

![narrow](https://cloud.githubusercontent.com/assets/5478779/23335595/eceaa92a-fbc0-11e6-9dff-018585f60ff0.png)
