### ISSUE TITLE
problem after upgrading to HASSIO 0.63.1

### ISSUE THREAD

**Issue by Gnaget2** [andrey-git/home-assistant-custom-ui#102]
### Checklist
- [X ] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Firefox 58.0.2, chrome 64.0.3282.140 HA ios app

**CustomUI version:** 20180126

**Home Assistant release (`hass --version`):** HASSIO 0.63.1

**Problem-relevant `configuration.yaml` entries:**
```yaml

```

**Problem-relevant Home Assistant log entries:**
```

```

**Any errors from browser Javascript console:**
```

```
Was running HASSIO 0.62.1 with som custom UI on my lights with local manual installation, was working fine, upgraded HASSIO today to 0.63.1 and now all ligts dot show upp in GUI, can see any errors in HA log

**Comment by Gnaget2** [comment]
downgraded HASS til 0.62.1 and now my GUI works fine again

**Comment by andrey-git** [comment]
I can't reproduce this.

Could you post your config (the customUI-related part)?
Please try with `/states?es5` and `/states?latest`

**Comment by Gnaget2** [comment]
I have tried both /states?es5 and /states?latest same result.

my config can be found here: https://github.com/Gnaget2/hassio/blob/master/configuration.yaml
and my UI config here: https://github.com/Gnaget2/hassio/blob/master/customize_glob.yaml

**Comment by andrey-git** [comment]
What does `hidden: {}` supposed to do? Try to remove it.

**Comment by andrey-git** [comment]
Unrelated note:
`stretch_slider: true` does nothing in `state_card_mode: single-line` mode

**Comment by Gnaget2** [comment]
hmm, i removed the hidden{} part and now it worked.

i added that one when i started using it to get it to work and it have been there all the way till now, but i close this one, thanks for support and KUTGW
