### ISSUE TITLE
How can I format extra_data_template?

### ISSUE THREAD

**Issue by uchagani** [andrey-git/home-assistant-custom-ui#104]
How can I customize the data in ```extra_data_template```?

I've tried the following:

```extra_data_template: ${state.toUpperCase()}```

```extra_data_template: ${return state.toUpperCase()}```

neither have worked.

### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome 64.0.3282.167

**CustomUI version:** 20180126

**Home Assistant release (`hass --version`):** 0.63.2

**Problem-relevant `configuration.yaml` entries:**
```yaml
customizer:
  custom_ui: local
```

**Comment by andrey-git** [comment]
`extra_data_template: ${state.toUpperCase()}`
`extra_data_template: return state.toUpperCase();`
