### ISSUE TITLE
option to exclude from *.* customize_glob?

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#109]
HI,

I use the 
```
"*.*":
  custom_ui_state_card: state-card-custom-ui
``` 
option in customize_glob. There is suspicion several entities don't behave as expected because if the customization. Could it be possible to have these excluded from the `*.* `for all?

a bit like in the Logger and logbook options:

```
exclude:
  sensor.dont_customize_1
  sensor.dont_customize_2
```

That way we can have the glob in place and be very precise which to exclude. 

Cheers,
Marius

**Comment by tringler** [comment]
I don't understand the question I think, because you can just override the `*.*` order by other definitions. In example after you applied
```
"*.*":
  custom_ui_state_card: state-card-custom-ui
```

You can override it by:
```
input_text.bathroom_music_dummy:
  icon: mdi:cast
  custom_ui_state_card: state-card-mini-media-player
```

**Comment by hvbhome** [comment]
HI,

My issue has gone, but the question is still valid. I would like to un-customize independent globally customized entities, in the example an independent sensor.

What you do is override the customization with another customization. I seek to un-customize entirely.

**Comment by andrey-git** [comment]
To uncustomize just override the value with null:
```
"*.*":
  custom_ui_state_card: state-card-custom-ui
input_text.bathroom_music_dummy:
  custom_ui_state_card: null
```

**Comment by hvbhome** [comment]
thanks, very helpful. exactly what i hoped for.
