### ISSUE TITLE
Installation or configuration issues？

### ISSUE THREAD

**Issue by BH4WHN** [andrey-git/home-assistant-custom-ui#111]
### Checklist
- [yes] I'm running the latest version of CustomUI ([Update guide] (https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating) ) or using a specific [release] (https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [yes] I tried to force-refresh (Ctrl + Shift + R / Ctrl + F5) the browser
- [yes] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

I followed the github tutorial to install custom_ui, but it does not work.
I can only see the lock icon, slider and badge can not be displayed.
Home Assistant 0.63.3
Custom UI 20180216
Chrome 64.0.3282.186（64bit)

configuration.yaml
[https://drive.google.com/open?id=1g5JjfIF-kfF3QshSA4bs08wacxcexoor](url)

customize.yaml
[https://drive.google.com/open?id=1iFuA2_xI9QQzDZnmHcKyfLlqe7LUbGut](url)

Chrome console
[https://drive.google.com/open?id=19Nq4GBdJF55ycGoDHmI4xqQM-5KU9pt2](url)

Fault screenshot
[https://drive.google.com/open?id=1I-6-2lMcM-UugKzp1D4JR75xcEl3HPng](url)

Any suggestions?Thanks!

**Comment by andrey-git** [comment]
what are the attributes of light.northbalcony_ceiling ? (From /dev-state screen)

**Comment by andrey-git** [comment]
When you click on the state card, do you see the brightness slider in the "More info" window?

**Comment by BH4WHN** [comment]
>what are the attributes of light.northbalcony_ceiling ? (From /dev-state screen)

[Entity]
light.northbalcony_ceiling
 [Attributes]
extra_badge: {
  "attribute": "power_consumption",
  "unit": "W"
}
supported_features: 0
state_card_mode: break-slider
confirm_controls_show_lock: true
custom_ui_state_card: state-card-custom-ui
friendly_name: N1

> When you click on the state card, do you see the brightness slider in the "More info" window?

When I click the status card, there is no brightness slider in the "More info" window.
screenshot
[https://drive.google.com/open?id=1dlZ6m9taW2izQJ_aZN6-IfTwZjy0_CGp](url)

@andrey-git Thanks for your reply!

**Comment by andrey-git** [comment]
There is no slider because `supported_features` doesn't include brightness, which is "1".
You should fill brightness_command_topic for that.

**Comment by andrey-git** [comment]
Also, your light doesn't have a `power_consumption` attribute, thus the badge doesn't appear.

**Comment by BH4WHN** [comment]
After I added the brightness topic, the slider can be displayed.Thank you very much!
