### ISSUE TITLE
feature request:  add templating to Unit of Measurement

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#114]
https://community.home-assistant.io/t/have-updater-updater-show-available-version/43089/11?u=mariusthvdb

trying to create a template for UoM to display the value of the sensor as follows:

```
sensors:
      ha_update_available:
        friendly_name: 'HA Update Available'
        unit_of_measurement: '{{states.sensor.ha_latest_version.state}}'
        value_template: >-
          {%- if states.sensor.ha_latest_version.state != "unavailable" and 
          states.sensor.ha_latest_version.state != states.sensor.ha_installed_version.state -%}
             Yes
          {%- else -%}
             No
          {%- endif -%}
        icon_template: >-
          {%- if states.sensor.ha_latest_version.state != "unavailable" and 
          states.sensor.ha_latest_version.state != states.sensor.ha_installed_version.state -%}
            mdi:alert-box
          {% else %}
            mdi:approval
          {% endif %}
```
won't work though, neither does the following customization:

```
homeassistant:
  customize:
    sensor.ha_update_available:
      state_card_mode: badges
      templates:
        unit_of_measurement: '{{states.sensor.ha_latest_version.state}}'
        theme: >
          if (state = 'Yes') return 'green_badge'; else return 'blue_badge';
```

![schermafbeelding 2018-02-27 om 14 59 07](https://user-images.githubusercontent.com/33354141/36732728-d4cedb52-1bce-11e8-86e4-fe4d0ffbd262.jpg)
![schermafbeelding 2018-02-27 om 14 59 21](https://user-images.githubusercontent.com/33354141/36732729-d4f80c2a-1bce-11e8-82db-fe4784aeab86.jpg)

Would be really cool if at all possible,
Thanks for having a look,
Marius

**Comment by fanaticDavid** [comment]
Try this:
```yaml
unit_of_measurement: ${entities['sensor.nas_total_size_volume_1'].state}
```
Templates in Andrey's Custom UI use JavaScript (client-side rendering), not Jinja (server-side rendering).

**Comment by hvbhome** [comment]
so cool!
thank you!!

![schermafbeelding 2018-02-27 om 16 00 32](https://user-images.githubusercontent.com/33354141/36735846-6e8892ee-1bd7-11e8-90ea-662bbce29a4f.jpg)
![schermafbeelding 2018-02-27 om 16 00 09](https://user-images.githubusercontent.com/33354141/36735854-743bdc00-1bd7-11e8-9a07-4214766421ed.jpg)

other than learning on the job is there a clear guideline that demonstrates the client and server side rendering differences? 
I am still insecure which tempting and/or customization i need now and then, and why ;-)

Guess i can at least close this feature request as solved! I knew it had to be possible, phew. 
Thanks again,
Marius

**Comment by fanaticDavid** [comment]
As far as I know, there is no guideline. I just use the [docs](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/templates.md), the issues in this repository (including the ones I posted myself) and sometimes the [forum](https://community.home-assistant.io/) to figure things out. It usually takes some trial and error, as I'm not too familiar with JavaScript. Other than that, I know from experience what Home Assistant allows me to do, and for what I need to resort to (a) custom UI.

I 'test' my code directly in Home Assistant as reloading the core config is enough to apply changes. In other words: it doesn't require restarting Home Assistant completely.

**Comment by RezzZ** [comment]
Hi Marius, can you share the complete solution? I'm trying your sensor from your first message but I believe it is missing the platform?

I currently have two sensors, one showing the installed version, the other shows the latest available. I would love to see a badge when an update is available
