### ISSUE TITLE
Change Color of command line switch on/off icons

### ISSUE THREAD

**Issue by shack31b** [andrey-git/home-assistant-custom-ui#116]
Hey,

is there a way to change the colors of the command line switches depending on their states? I would like to use a different color for each of them, not only influenced by the main color. Haven't found something like this yet.

![grafik](https://user-images.githubusercontent.com/36752722/36824702-f6017254-1d03-11e8-8a60-c8f7c44ebc97.png)

Would like to do it on the navigation bar likewise.

![grafik](https://user-images.githubusercontent.com/36752722/36824969-4d25d3f8-1d05-11e8-838a-8c834483d765.png)

Keep up the great work!
Kind regards

Tim

- [x] I'm running the latest version of CustomUI (
Home Assistant release:** 0.63.3

**Comment by tringler** [comment]
You have a working theme, which applies to these icons basically, but you are asking how to apply different thmes dynamically by custom-ui right?

**Comment by shack31b** [comment]
Thanks for your reply. I created this theme but found no way to change the color of the marked icons seperately. So I want to colorize the "off"-state in blue and the "on"-state in yellow ifg they are active. 
Furthermore the Icons in the navigation bar are way to dark, so I want to change them as well.

**Comment by tringler** [comment]
That means your problem is more CSS problem in HASS than a problem how to apply the style by custom-ui right?

**Comment by shack31b** [comment]
I'm new to github, so if I think about it ... yeah, you're right. :') 
Wasn't sure where to place my question, may this is the proper spot to place my question:
[https://github.com/home-assistant/home-assistant-polymer/issues](url)
I'm not really comfortable with the provided docs, so you may can excuse.

**Comment by shack31b** [comment]
Solved:
https://github.com/home-assistant/home-assistant-polymer/issues/965
