### ISSUE TITLE
Custom UI not appearing on Configuation page

### ISSUE THREAD

**Issue by gadgetchnnel** [andrey-git/home-assistant-custom-ui#122]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome 64

**CustomUI version:** 20180216

**Home Assistant release (`hass --version`):** 0.65.4

**Problem-relevant `configuration.yaml` entries:**
```yaml
customizer:
  custom_ui: hosted

config:

customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
      show_last_changed: true
```

**Problem-relevant Home Assistant log entries:**
```

```

**Any errors from browser Javascript console:**
```

```
The Custom UI configuration options are not appearing on the Configuration page. Using the Debug version and stepping through the code I can see that it reaches the following code in updateConfigPanel:

```
const ironPages = window.customUI.lightOrShadow(haPanelConfig, 'iron-pages');
    if (!ironPages) return;
```
ironPages is null at that point and so it returns from the function without updating the config panel. Has the styling of the Configuration page changed and Custom UI needs updating for this or have I missed something?

**Comment by hvbhome** [comment]
just to confirm Custom ui is missing indeed. Theme setting to Backend-selected is also unavailable, maybe related?

**Comment by brianhanifin** [comment]
I haven't been able to get CustomUI to show up either.

**Comment by stealthcopter** [comment]
+1 on this

**Comment by mohesles** [comment]
+1

**Comment by cmille34** [comment]
+1

**Comment by ebfio** [comment]
+1

**Comment by mohyat** [comment]
+1
