### ISSUE TITLE
Pop-up of detail page whenever a button is clicked

### ISSUE THREAD

**Issue by travisaaron** [andrey-git/home-assistant-custom-ui#125]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] I'm using IOS App to reproduce. Chrome Browser does not have this issue.

**Browser + Version:** iPhone 6s Plus, iOS 10.3.3

**CustomUI version:** Updated as of 30 March 2018 

**Home Assistant release (`hass --version`):** 0.65.6

Recently I updated to the latest Home Assistant to 0.65.6 and noticed that the on, off buttons that I created start to pop-up the detail page whenever it is clicked. This does not happened prior to the update because “ev.stopPropagation();” is used as advised.

How do I now stop that pop-up from appearing? For example if I press Storeroom Light “ON”, the detail page will appear. I will need to close it in order to go back to the main.

![](https://community-home-assistant-assets.s3-us-west-2.amazonaws.com/original/3X/c/8/c805f8fe6b529eb791231b5d6f62b58d1dc324fc.png)

![](https://community-home-assistant-assets.s3-us-west-2.amazonaws.com/original/3X/2/0/2014e172a115ad3712aa2de0963139ce08245f0b.png)

**Comment by andrey-git** [comment]
The UI doesn't look familiar.
Could you post the relevant config part?

**Comment by travisaaron** [comment]
The UI is from the IOS Home Assistant App. The state-card-custom I used is as below for reference. Another guy from Home Assistant Community advised to change the "on-tap" to "on-click" and this is resolved. 

``` html
<dom-module id="state-card-custom_fan1">
  <template>
    <style is="custom-style" include="iron-flex iron-flex-alignment"></style>
    <style>
      :host {
        line-height: 1.5;
      }
      paper-button {
        min-width: 29px;
        height: 30px;
        background-color:#f3f3f3
      }
    </style>

<div class='horizontal justified layout'>
  <state-info state-obj="[[stateObj]]"></state-info>
  <paper-button-group>
      <paper-button on-tap="btnlow">L</svg></paper-button>
      <paper-button on-tap="btnmed">M</svg></paper-button>
      <paper-button on-tap="btnhigh">H</svg></paper-button>
  </paper-button-group>
</div>
</template>
</dom-module>
<script>
        Polymer({
          is: 'state-card-custom_fan1',
          properties: {
            hass: {
              type: Object,
            },
            stateObj: {
              type: Object,
            },
          },

          btnlow: function (ev) {
            this.setVol('fan_speed_low', ev);
          },
          btnmed: function (ev) {
            this.setVol('fan_speed_med', ev);
          },
          btnhigh: function (ev) {
            this.setVol('fan_speed_high', ev);
          },

          setVol(vol,ev) {
            var serviceData = {entity_id:('scene.'+vol)};
            this.hass.callService('scene', 'turn_on', serviceData);
            ev.stopPropagation();
  },

});
</script>
```
