### ISSUE TITLE
WebApp in homeassistant card, possible with Custom UI?

### ISSUE THREAD

**Issue by jmgarciamari** [andrey-git/home-assistant-custom-ui#130]
I have latest version of Home assistant, I've found some projects using this custom ui, but I'm unable to show a webapp (HTML+JS+CSS) in a homeassitant state card (not panel) and read sensors values from this app, I've readed docs but I'm stucked...Can someone give a hand? I only want to put in HTML file style and script tags and show in a card...Thanks

**Comment by andrey-git** [comment]
To show custom content in a state-card you need to make a custom ui: https://developers.home-assistant.io/docs/en/frontend_creating_custom_ui.html

This repo is for one such implementation which does many things but doesn't show custom content.

For help on writing custom ui you should use the [forum](https://community.home-assistant.io/)

**Comment by jmgarciamari** [comment]
Yes, I've run succesfully the example but for some reason it only shows groups in a text area and If I try to pass sensors instead group breaks HA. I think that I've not understanding...
