### ISSUE TITLE
Home Assistant 0.70 update to Polymer 3.0

### ISSUE THREAD

**Issue by kukudemajia** [andrey-git/home-assistant-custom-ui#132]
![f_70k7v w i tsecz8 04cl](https://user-images.githubusercontent.com/17118600/40269135-5b1f4800-5bac-11e8-8ecb-8bd77f356d49.png)

![r0 pcd82ubs298bp x2 of](https://user-images.githubusercontent.com/17118600/40269129-5043fb6a-5bac-11e8-8184-ce4d018a4f43.png)
## The Polymer 3.0 API is almost 100% backward compatible with Polymer 2.x—the only changes are removing APIs related to HTML Imports (such as importHref), and converting Polymer's API to be module-based rather than globals-based.

# home-assistant-polymer Version bump to 20180519.0

**Comment by andrey-git** [comment]
Fixed in 20180521
