### ISSUE TITLE
HASS 0.70 hassUtil UDON'T WORKING How do I have relativeTime and parameters coexist?

### ISSUE THREAD

**Issue by KleinerSource** [andrey-git/home-assistant-custom-ui#135]
It was done before
        extra_data_template:
          - "${attributes.load_power !== 0 ? ('Load: ' + attributes.load_power + 'W') : ''}"
          - "${attributes.load_power !== 0 ? ('Total: ' + attributes.power_consumed / 1000 + 'W') : ''}"
          - "${window.hassUtil.relativeTime(new Date(entity.last_changed))}"

but 0.70  last  ${window.hassUtil.relativeTime(new Date(entity.last_changed))}" don't working
What should I do?

**Comment by fatuuse** [comment]
Change to this:
https://community.home-assistant.io/t/custom-ui-last-time-automation-was-triggered/41820/39

**Comment by KleinerSource** [comment]
They can't show it at the same time.
