### ISSUE TITLE
Debugging custom-ui errors

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#143]
Hello,

how is the right way to debug custom-ui? Currently I have the behaviour that something in my customization seems to trigger an error and in the home assistant I see a message which contains I assume the whole JS code.

I'm unable to find the error in that message? Any hints how to do that?

Thanks, Thomas

**Comment by andrey-git** [comment]
If you use customizer you can use:
```
customizer:
  custom_ui: debug
```

Or use `https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-dbg.html` as `extra_html_url
