### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by uchagani** [andrey-git/home-assistant-custom-ui#145]
Getting the following error in the dev panel.  multiple errors of the same thing.  I've cleared application data and all cache (for the entire browser).

```
https://xxxxxxxxxxxx.duckdns.org/frontend_es5/app-decf9df57101156d4bdfa688327fc24a.js:2:16401 TypeError: undefined is not an object (evaluating 'window.hassUtil.computeDomain')
```

### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 67.0.3396.99

**CustomUI version:** 20180716

**Home Assistant release (`hass --version`):** 0.73.2

**Problem-relevant Home Assistant log entries:**
```
https://xxxxxxx.duckdns.org/frontend_es5/app-decf9df57101156d4bdfa688327fc24a.js:2:16401 TypeError: undefined is not an object (evaluating 'window.hassUtil.computeDomain')
```

**Comment by andrey-git** [comment]
CustomUI no longer uses `hassUtil`, so either it is a caching issue or maybe you are using it in your config?
