### ISSUE TITLE
Odd behaviour when hiding side panel in HA

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#15]
I don't know if the fact that the affected strings have two words rather than one is part of the issue, but that's the only thing I see that's different about them.

With side panel:
![screen shot 2017-06-26 08 45 52 pm](https://user-images.githubusercontent.com/3755059/27536025-90309ff6-5ab0-11e7-85c2-9f802a5f2b62.png)

Without side panel:
![screen shot 2017-06-26 08 46 12 pm](https://user-images.githubusercontent.com/3755059/27536036-9ff3fe24-5ab0-11e7-8925-ecbf733a4f0b.png)

This is affecting both Chrome and Safari on Mac.

**Comment by mihalski** [comment]
Update with my latest config. This also seems to happen when manually resizing the window.
All good:
![image](https://user-images.githubusercontent.com/3755059/27770032-346850fe-5f7b-11e7-84ab-3f6cf2c90b84.png)
Gone wonky:
![image](https://user-images.githubusercontent.com/3755059/27770046-6ee84b6c-5f7b-11e7-82e0-9c8f118be400.png)
Bug in polymer?

**Comment by randellhodges** [comment]
I have, what might be related, a similar issue. I have the option to show the sliders if there is space. When I go to the UI, when I first see a tab, it looks fine, the sliders are hidden. If I click another tab, then go back, it displays the sliders.  I don't get this with all tabs. It is like the render isn't triggered at the right time when clicking tabs.

**Comment by randellhodges** [comment]
Here is a quick video of what I was talking about. I hope I'm not jacking the thread. Just thought it might be related.
https://youtu.be/V3W31s7mmsc

**Comment by andrey-git** [comment]
@randellhodges Do you still have this issue?

**Comment by andrey-git** [comment]
Found the bug - will be fixed in the next release.

**Comment by randellhodges** [comment]
Oh nice. I had turned off sliders a while back. I'll give them a go later. Thanks for coming back to this!

**Comment by andrey-git** [comment]
Fixed in 20171214
