### ISSUE TITLE
Uncaught TypeError after upgrading to HA 0.84.1

### ISSUE THREAD

**Issue by serbani** [andrey-git/home-assistant-custom-ui#160]
### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Chrome 70.0.3538.110**

**CustomUI version: 20180831**

**Home Assistant release (`hass --version`): 0.84.1** 

**Problem-relevant Home Assistant log entries:**
```
http://somehost:8123/local/custom_ui/state-card-custom-ui.html:27:15926 Uncaught TypeError: Class extends value undefined is not a constructor or null
```

**Any errors from browser Javascript console:**
I've tried switching to the debug version but none of the instructions worked.
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (dynamic-with-extra.js:10)
    at i (bootstrap:19)
    at bootstrap:68
    at bootstrap:68
```

What I observe: all cards are empty.

**Comment by alegiovannelli** [comment]
I also found the error after upgrading to the latest version. The error of visualization I found only on my smartphone with the browser Chrome, also with the stock one, on the desktop PC no errors.

`ERROR (MainThread) [frontend.js.latest.201812110] https://xxxxxxxx/local/custom_ui/state-card-custom-ui.html:27:15926 Uncaught TypeError: Class extends value undefined is not a constructor or null`

**Comment by andrey-git** [comment]
Fixed by release 2018-12-17
