### ISSUE TITLE
State badge does not work anymore since 0.88

### ISSUE THREAD

**Issue by jncanches** [andrey-git/home-assistant-custom-ui#169]
Since State badge has been converted to TypeScript [(link to commit),](https://github.com/home-assistant/home-assistant-polymer/pull/2712) icon_color in templates does not work anymore

The problem is that hooks.js redefine _updateIconAppearance function of StateBadge custom element but it does not exists anymore. I think that now, the function to override now is updated()

**Comment by jncanches** [comment]
Same problem as issue 168

**Comment by andrey-git** [comment]
Duplicate of #168
