### ISSUE TITLE
Context-aware group card titles?

### ISSUE THREAD

**Issue by bgehrich** [andrey-git/home-assistant-custom-ui#18]
Is it possible to change the displayed title of a group that is shown as a card within a view by applying a friendly_name to the group entity within the parent view's context?  Changing the displayed name of a group that is included within another group is working properly, but I have been unable to change the displayed title of a group included directly in a view within the context of the view (changing the displayed title with a global "friendly_name" does work, however).  I'm not sure if I am applying the customizations incorrectly, or if I am trying to do something not currently possible.  

Thanks for any info you can provide.  If my problem description doesn't make sense I can provide full configuration details.

**Comment by andrey-git** [comment]
This is currently not supported. I'll look whether this can be implemented.

**Comment by tbrasser** [comment]
I'd like this feature as well.  For example, I have a group living room lights, that I would like to name just 'lights' in the living room view, and just 'living room'  in the lights view.

**Comment by andrey-git** [comment]
Implemented
