### ISSUE TITLE
Can’t get sliders to work with Hue Lights 

### ISSUE THREAD

**Issue by jer78** [andrey-git/home-assistant-custom-ui#20]
Not sure what I’m doing wrong. Can’t see anything in the error log either. The sliders are always at 0 and don’t change the brightness when I move them. 

Here’s my config: 

homeassistant:
  customize_glob:
    light.*:
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      hide_control: false
      show_last_changed: false
      slider_theme:
        min: 0
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false

**Comment by jer78** [comment]
Sorry the formatting is off here but it’s correct in my yaml file. Using my phone to post :(

**Comment by andrey-git** [comment]
The config is probably OK, but please use "```" before and after config text to format it: https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by acateon** [comment]
Dont know if it has something to do with the new HA release but I just tried it out and the dimmer slides don't work.

```2017-07-05 22:27:44 ERROR (MainThread) [homeassistant.components.websocket_api] WS 2923331152: Message incorrectly formatted: required key not provided @ data['service']. Got None ```

These keep firing when moving the slider...

**Comment by clemon79** [comment]
I don't think it's just Hue sliders...I have a custom template I wrote for a HomeBrite Bluetooth light that is having the same issue. On and off works, sliding the slider has no effect and often quickly pops up a lost connection warning.

**Comment by gunnarbeutner** [comment]
I'm seeing the same problem here. Resetting my Git repository to '4539bf4 Use updated mixin' seems to fix this.

It seems like some change in '637b74c Support for context-aware attributes. Also on display and togle type cards.' broke sliders.

**Comment by andrey-git** [comment]
I pushed a new version. Could someone check if it fixes the issue?

**Comment by gunnarbeutner** [comment]
Works for me. Thank you very much. :)

**Comment by clemon79** [comment]
Mostly works for me. Is there a way to define the range of the slider? By default it seems to be 0 to 100, but the default Brightness slider with a light.template goes from 0 to 255.

**Comment by gunnarbeutner** [comment]
I noticed that as well, here's what I use:

```
  customize_glob:
    light.*:
      custom_ui_state_card: custom-ui
      state_card_mode: single-line
      hide_control: true
      slider_theme:
        min: 0
        max: 255
```

**Comment by clemon79** [comment]
Aw yeah, perfect! Thanks much!

**Comment by acateon** [comment]
Still got the same error...

```2017-07-06 12:17:23 ERROR (MainThread) [homeassistant.components.websocket_api] WS 2867411376: Message incorrectly formatted: required key not provided @ data['service']. Got None ```

```  customize_glob:
    light.*:
      custom_ui_state_card: custom-ui
      state_card_mode: break-slider
      stretch_slider: true
      hide_control: false
      show_last_changed: false
      slider_theme:
        min: 0
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false```

**Comment by andrey-git** [comment]
@acateon
Could you open browser dev tools (Ctrl+Shift+I or F12 on Chrome) and check which CustomUI version is printed in the console (and if there are errors there)

**Comment by acateon** [comment]
Using CustomUI 20170702

```aper-drawer-panel is deprecated. Please use app-layout instead!
ready @ frontend-bdcde46….html:5
_readySelf @ frontend-bdcde46….html:1
_ready @ frontend-bdcde46….html:1
_readyClients @ frontend-bdcde46….html:1
_ready @ frontend-bdcde46….html:1
_readyClients @ frontend-bdcde46….html:1
_ready @ frontend-bdcde46….html:1
_tryReady @ frontend-bdcde46….html:1
_constructorImpl @ frontend-bdcde46….html:4
r @ frontend-bdcde46….html:4
stamp @ frontend-bdcde46….html:4
_ensureInstance @ frontend-bdcde46….html:4
_render @ frontend-bdcde46….html:4
complete @ frontend-bdcde46….html:2
boundComplete @ frontend-bdcde46….html:2
_atEndOfMicrotask @ frontend-bdcde46….html:2
window.MutationObserver.observe.characterData @ frontend-bdcde46….html:2
state-card-custom-ui.html:1 Using CustomUI 20170702
states:1 Uncaught (in promise) undefined```

**Comment by acateon** [comment]
Clearing the browser cache solved the problem. Working fine now.

**Comment by jer78** [comment]
Awesome! Update fixed it. Thanks
