### ISSUE TITLE
Extra data support for state as well as attribute

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#21]
Is there a way to get the extra data template to support sensor states as well as attributes?
I've come across man use cases where this would be ideal.

The badge can show either a state or an attribute.

**Comment by mihalski** [comment]
I just realised that states.sensor.state SHOULD be able to do what I requested but I can't seem to be able to get it to work.

**Comment by andrey-git** [comment]
Dup of #19
