### ISSUE TITLE
REQUEST: Media Player Custom UI

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#23]
Here is an example of our pain:
https://community.home-assistant.io/t/hide-cover-art-in-media-players/9826
https://community.home-assistant.io/t/tts-causes-media-player-album-art-bounce/19358

For starters just the ability to disable cover art would be INCREDIBLY useful.

Regards,
Michal

**Comment by andrey-git** [comment]
In the first thread balloob was quoted saying he is no topposed to this feature, so no reason to put it in customUI

The second thread is about a bug, also not related to customUI

**Comment by mihalski** [comment]
Sorry. Late was late at night.

I MEANT to have linked this:
https://github.com/home-assistant/home-assistant/issues/1915
Where the conclusion from balloob was agreement that this belonged in a custom ui state card.

Regards,
Michal

**Comment by andrey-git** [comment]
The album art can be disabled via `customize` (I responded on the first thread).
Bouncing album art is bug, but unrelated to customUI.
