### ISSUE TITLE
Unavailable devices not showing last update time

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#24]
Devices that are no longer available are not showing the last update time. For example this LIFX light:
![screen shot 2017-07-25 09 24 11 pm](https://user-images.githubusercontent.com/3755059/28570045-aa5ae842-717f-11e7-815c-709d8a6c78f1.png)
However the information IS there:
![screen shot 2017-07-25 09 22 22 pm](https://user-images.githubusercontent.com/3755059/28570008-8df0f87c-717f-11e7-98a4-77f099bb5d7e.png)
Is there any way to have it displayed in these circumstances?

**Comment by andrey-git** [comment]
Homeassistant fix was merged and will be released in 0.50
CustomUI fix was merged and will be available in the next release (in a few day hopefully)
