### ISSUE TITLE
QUESTION: Is it possible to have different customisations for different groups?

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#25]
For example, with a battery powered motion sensor I may want to have the last triggered time visible as additional data for most groups, but the battery level attribute when in the battery group.

**Comment by andrey-git** [comment]
Context-aware attributes works for all attributes, including `show_last_changed` and `extra_data_template`

**Comment by mihalski** [comment]
Thank you.. This makes my day.. I thought I was over-reaching.
