### ISSUE TITLE
Is there an option to template themes?

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#26]
Not an issue.  Just a question/feature request.
With the new frontend theme option and the custom ui, it would be nice if we could template the color (or any other attribute) of some entities (badges, text, background etc.) depending on their value.  
However, I think that is a lot harder to implement. Is there some work on this yet? I am thinking to start something.
Also it could be a nice addition if we could change the font type, weight, color, background color etc. of entities or/and state cards.
Thanks.
Some examples below (could apply for motion sensors, alarm, temperature etc.).
<img src="https://user-images.githubusercontent.com/8059190/28863714-55cb53c0-776a-11e7-9696-87421f5cce5f.png" width="300"><img src="https://user-images.githubusercontent.com/8059190/28863855-c785a8d0-776a-11e7-944e-9ffcfdd25dea.png" width="300">
<img src="https://user-images.githubusercontent.com/8059190/28864865-3d1fd0ea-776e-11e7-953c-bb5f1469d079.png" width="300">

**Comment by andrey-git** [comment]
There are several issues here:
1) *What you can theme*. This belongs to the main UI. There are few PRs improving that: home-assistant/home-assistant-polymer#361 home-assistant/home-assistant-polymer#366
2) *Theme single entity and not the whole UI*. This is already supported by CustomUI
3) *Theme conditionally*. This could be done via dynamic customization.
For example if you want to color the storage yellow when it is >50%:
  3.1 Define a 'yellow' theme.
  3.2 Define an automation that sets 'theme: yellow' attribute on storage when storage goes above 50%.
  3.3 Define an automation that clears theme attribute on storage when storage is below 50%.   
 
I don't think the attributes can be existing jinga2 templates as those are specifically computed server-side for relevant attributes and not for customization attributes.

We could either implement our own minimalistic template language or pull in jinga2 JS parser. I don't think it is worth the complication at this stage.

Another option is to implement this in `customizer` custom component. You are welcome to send a PR for that :)

**Comment by covrig** [comment]
Thanks for the fast and detailed reply. I appreciate it. I am wondering what is the best option for all this.

Extending your theme platform to include other features (font weight, size, background-color etc.) beside the color would be an excellent addition to have. I understand the UI limitation. 

I tried the automation approach for conditional themes and it works (I am a bit limited by the CSS), but it gets out of hand if I need to set up an automation for each entity that I want to customize.

[Floorplan for Home Assistant](https://github.com/pkozul/ha-floorplan) does something interesting with the templates. It  is a bit far from CustomUI approach but it could be interesting to implement a similar solution.
```       name: humidity
          entities:
             - sensor.humidity_158d00010303da
             - sensor.humidity_158d0001030b38
             - sensor.humidity_158d00010c39d6
             - sensor.humidity_158d00010d5c13
             - sensor.humidity_158d00010d5e5c
          text_template: '${entity.state ? Math.ceil(entity.state) + "%": "undefined"}'  
          class_template: '
            var hum = parseFloat(entity.state.replace("%", ""));
            if (hum < 50)
              return "low";
            else if (hum < 70)
              return "med";
            else
              return "high";
            '
```
```class_template``` could be replace by theme, where: low, med, high are options.

**Comment by andrey-git** [comment]
Implemented!

**Comment by covrig** [comment]
Wow! You were busy today. :) Sorry...
Thank you for your hard work. Cheers.

**Comment by bramkragten** [comment]
Btw, you can set fonts, font weight and font size with themes:

Try:
````
      paper-font-body1_-_font-family: monospace
      paper-font-body1_-_font-size: 10px
      paper-font-body1_-_font-weight: bold
      paper-font-body1_-_line-height: 50px
      paper-font-subhead_-_font-family: monospace
      paper-font-subhead_-_font-size: 30px
      paper-font-subhead_-_font-weight: bolder
      paper-font-headline_-_font-family: monospace
      paper-font-headline_-_font-size: 20px
      paper-font-headline_-_font-weight: lighter
```

**Comment by covrig** [comment]
I didn't even bother to try or check the code, before asking. I feel stupid. :( Thanks for letting me know
