### ISSUE TITLE
Attributes with spaces

### ISSUE THREAD

**Issue by kuduka** [andrey-git/home-assistant-custom-ui#29]
I'm trying to use custom-ui in order to show some attributes with spaces but I'm unable to do it.

I've opened an [issue](https://github.com/home-assistant/home-assistant/issues/8808) with HA but they redirected me here :)

It could be possible for custom-ui to support attributes with spaces?

**Comment by andrey-git** [comment]
You can use `extra_data_template: ${attributes['power_consumed']}`

**Comment by mihalski** [comment]
I can vouch that it works. I had a similar issue with battery_level until I figured it out.

**Comment by kuduka** [comment]
That works for me too, thanks.
