### ISSUE TITLE
Changes to extra_data_template

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#30]
Would it be possible to have template examples for states from another entity? I'm having some trouble getting the new syntax right.

For example, I was previously using "${state.sensor.office_energy_today_cost}" to display a dollar value.. What would the new syntax be?

I also noticed a change in behaviour for when I used an attribute of a light (effect) within the extra_data_template. Previously when the light was off it would show the time since state change (since effect was unavailable), and now it shows "undefined".

**Comment by andrey-git** [comment]
I added more examples here: https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/templates.md

**Comment by mihalski** [comment]
Thank you. That has been very instructional.. I would have NEVER figured it out without those examples.

Just to confirm, my two options for achieving the above would be:
```
return '$' + entities['sensor.office_energy_yesterday_cost'].state;
```
or
```
${'$' + entities['sensor.office_energy_today_cost'].state}
```
Am I doing it right? It seems to work.

**Comment by andrey-git** [comment]
You don't need to add '$' to variables

**Comment by mihalski** [comment]
I do if I want them to display with it like so:
![screen shot 2017-08-16 02 03 14 pm](https://user-images.githubusercontent.com/3755059/29346863-b6909202-828b-11e7-8431-0aa45baec55b.png)

**Comment by andrey-git** [comment]
Oh, I didn't realize you want an actual dollar sign.
