### ISSUE TITLE
Custom Ui partially broken with 0.51.1

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#31]
Sliders don't show anymore and all customized entities don't align properly to the right of the state card.
Thanks.

![image](https://user-images.githubusercontent.com/8059190/29248173-d31b6c98-8011-11e7-8cd7-fde4d39fa646.png)

**Comment by andrey-git** [comment]
Are you on the latest version? The version is printed into the browser dev console.

**Comment by covrig** [comment]
Yes, I am on the latest version.
![image](https://user-images.githubusercontent.com/8059190/29248207-d91cb2f4-8012-11e7-97e6-7945b32c0ed1.png)

**Comment by andrey-git** [comment]
If on latest (20170805), then what browser is it?

**Comment by covrig** [comment]
Latest Chrome. The same in Chrome mobile. Also in latest IE.

**Comment by andrey-git** [comment]
I think this was fixed in customUI 20170805

**Comment by fanaticDavid** [comment]
I saw this behaviour too, but I wasn't using the latest release of Custom UI yet. So I upgraded to the latest version, and I removed my Home Assistant instance from my Firefox cache (via "Forget this website"). Now, it's working just fine again.

**Comment by covrig** [comment]
Thanks for the help. It was the cache to blame.
