### ISSUE TITLE
New frontend classes (0.51) not working with theme_template

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#33]
Some new frontend classes where added in 0.51 (e.g. background color state card -  ```paper-card-background-color```. 
Some other work (e.g. ```paper-item-icon-color```).
Maybe it is just me but I can't get something similar to the picture below (with theme_template applying a background color to a single entity).
I can work on it, but I would need a start point. Sadly, I don't have the time these days to understand the code. Thanks.
![image](https://user-images.githubusercontent.com/8059190/29252428-62fabaa8-8067-11e7-8843-2fc737fe159f.png)

**Comment by andrey-git** [comment]
The picture below is applying a global theme?
Does applying a constant per-entity `theme` works for you?

**Comment by covrig** [comment]
Forget about the previous picture. I was showing there a few more things there than I should have. Sorry for the confusion. (However, everything was a per-entity theme.)
To keep it simple, I wan't to obtain something similar to the new picture (in the picture - the yellow background color was added manually, not with themes). 
The ```theme_template``` does not recognize the new class ```paper-card-background-color```. The background color is not added. 
It might be the same for other new classes.

**Comment by andrey-git** [comment]
You shouldn't pass any classes to `theme_template`.
It should evaluate to a theme *name* just like a static `theme` per-entity attribute.

**Comment by covrig** [comment]
I am not. I should not have used the word class.
'''paper-card-background-color''' attribute works for general themes.
However, per entity it does not (with or without a '''theme_template'''. I just want to replicate the picture.

**Comment by covrig** [comment]
@andrey-git I will close this ticket and open a proper one. I didn't think it trough when I opened this one. Sorry.
