### ISSUE TITLE
Custom UI on iOS not showing

### ISSUE THREAD

**Issue by redoz** [andrey-git/home-assistant-custom-ui#36]
I've included the slider UI for my dimmers which works fine in Chrome (desktop and android phone), but it won't show in Safari on iOS.

Docs seemed to indicate this should work in in Home Assistant > 0.41 and I'm currently on 0.52.

Android:
![image](https://user-images.githubusercontent.com/1670030/29745814-c649b8b2-8ac5-11e7-82c3-dbfc789fabee.png)

iOS:
![image](https://user-images.githubusercontent.com/1670030/29745845-2dba6992-8ac6-11e7-9697-1a95329bd69c.png)

**Comment by andrey-git** [comment]
Which version of ios is that?
Do you have a Mac? If yes, does it work in Safari on Mac?

**Comment by redoz** [comment]
It's iOS 9.3.2. And no, afraid I don't have any other Apple devices to test with.

**Comment by andrey-git** [comment]
Did you intend to close this?

**Comment by redoz** [comment]
Yeah, I noticed the requirements said iOS 10, and the phone is still on 9. As it's not supported the issue isn't valid anymore.
