### ISSUE TITLE
Problems after HA 0.53.0

### ISSUE THREAD

**Issue by roflcoopter** [andrey-git/home-assistant-custom-ui#38]
This no longer works for me since HA 0.53.0

I ran the update.sh script to get the latest files.

Then i changed in my config from 
`custom_ui_state_card: custom-ui`
to
`custom_ui_state_card: custom-ui-state-card`

and i added this to my configuration.yaml
```
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
```

This just results in all my cards being empty, no entities shown.

Am i doing something wrong or is it broken?

**Comment by andrey-git** [comment]
It should be `custom_ui_state_card: state-card-custom-ui`

**Comment by randellhodges** [comment]
@andrey-git Not sure if I should hijack this, or create separate issues.

I think I have everything updated. I don't get blank cards and things "seem" to work, but I noticed that my group specified entity names are no longer working, and when I click on an entity to bring up the modal card, some things are missing and I see errors inside the developer tools.

"Cannot read property 'updateStyles' of undefined"

I'm going to try removing everything and updating again to see if maybe something didn't come down when I did a ./update.sh

**Comment by andrey-git** [comment]
@randellhodges 
When does the error appear?

**Comment by fanaticDavid** [comment]
I've observed similar behaviour to @randellhodges : 

- Group specific friendly names don't work
- In Firefox, clicking on an entity does nothing (doesn't bring up the entity's history) and once I've clicked on an entity I cannot open the sidebar anymore until I reload the page
- In Chrome, clicking on an entity only brings up that entity's history once, every consequent click on an entity does nothing

I'll work on showing the erros in the console...

**Comment by fanaticDavid** [comment]
Firefox shows no errors when loading the page, but the console shows the following after clicking on an entity:

<img width="1792" alt="schermafbeelding 2017-09-09 om 20 43 40" src="https://user-images.githubusercontent.com/20402931/30242987-752a7750-95a1-11e7-9e47-dcfd1e68c504.png">

Chrome console when loading the page:

![schermafbeelding 2017-09-09 om 20 46 38](https://user-images.githubusercontent.com/20402931/30242996-9b2305bc-95a1-11e7-9642-80fe631ff259.png)

Chrome console after clicking on an entity:

![schermafbeelding 2017-09-09 om 20 47 07](https://user-images.githubusercontent.com/20402931/30243000-b2ae266c-95a1-11e7-9c23-c52f221d2e20.png)

I hope this helps...

**Comment by randellhodges** [comment]
Thank you @fanaticDavid for providing better information than I did. That is exactly what I am seeing as well.

**Comment by andrey-git** [comment]
Please fetch 20170910

**Comment by randellhodges** [comment]
Looks good!

**Comment by fanaticDavid** [comment]
Same here (tested in Firefox): group specific friendly names work, and I can click on entities again to load their history 👍 

Great and fast work! Thanks, @andrey-git !
