### ISSUE TITLE
No custom UI card

### ISSUE THREAD

**Issue by juan11perez** [andrey-git/home-assistant-custom-ui#41]
Good day, installed 0.53 and followed the instructions for Custom UI but can't get the custom UI card in the panel. Any suggestions?

**Comment by andrey-git** [comment]
What do you get? Could you attach a screenshot?

Any errors in HA logs? Any errors in browser dev console?

**Comment by juan11perez** [comment]
Ok Andrey, so when I installed your package I was logged in as Pi@....., so when I tried the local install it was refused access, so I moved to sudo su and installed.

Last night as I was trying to guess the problem I decided to chmod 755 the respective configuration folders and left it.

This morning I checked and the custom UI card is there, but inside the configurator. Guess that's ok.

See attached 



One more question, the Groups card is not appearing, but I read a thread from you that's a current "issue" to be corrected?

Regards
Juan

**Comment by juan11perez** [comment]
Andrey, see attached. The card doesn’t appear in the frame panel. No errors at all.














Regards/Saludos
Juan

**Comment by tomoqv** [comment]
I just noticed that the custom UI cards don't show in Firefox 55.02. They look fine in Google Chrome though.

**Comment by andrey-git** [comment]
@tomoqv are you on HA 53.1? Any errors in dev console? Did you clear cache?

**Comment by tomoqv** [comment]
Yes, on HA 53.1. Cleared cache in FF and now UI cards show again, thanks.

**Comment by andrey-git** [comment]
@juan11perez Images sent via email don't appear in the issue tracker

**Comment by juan11perez** [comment]
Andrey, i no longer have an issue. Thank you.
