### ISSUE TITLE
state_card_mode: badges for binary_sensor

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#42]
Hello,

it is not possible to use ` state_card_mode: badges` for binary sensors? If I use it for a binary sensor it is not displayed as badge in a group.

Any hints?

Thanks!

**Comment by andrey-git** [comment]
Could you paste relevant parts of your config?
What is your customUI and Homeassistant versions?

**Comment by tringler** [comment]
@andrey-git Sorry - it went out that if I put the binary sensors in a group and add the `state_card_mode: badges` to the group customization instead of th sensor customization itself, it works.

**Comment by andrey-git** [comment]
Note that in the latest CustomUI version `state_card_mode: badges` should work on individual sensors too.
