### ISSUE TITLE
Change dynamically badge description by extra_data_template

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#46]
Hello,

would it be possible to output a value by extra_data_template if the entity is displayed as a badge?
Just like:
`extra_data_template: if (entities['binary_sensor.climate_livingroom_windowshutter'].state === 'off') return 'Closed'; else 'Opened';`

Thanks in Advance!

**Comment by andrey-git** [comment]
You mean in addition to entity name? Or instead of entity name? Or do you want to replace the value that is shown inside the circle?

**Comment by tringler** [comment]
I mean instead of the entity name, because sometimes I want to display the value instead of the name. The name is represented by the icon, (windowshutter, climate, light,...), the status is represented by the theme (on, off) and I want to output the value (opened/closed, current temperature,...)

**Comment by andrey-git** [comment]
I have just release 20170927 where you can templatize attributes and state to your liking.

Enjoy :)
