### ISSUE TITLE
Is it possible to change icon color?

### ISSUE THREAD

**Issue by nalipaz** [andrey-git/home-assistant-custom-ui#47]
I got everything setup properly and am able to change background and font color, but am a little unsure if it is possible to change the icon color without just changing the icon altogether? It seems like it should be since they are material design icons.

Thanks!

**Comment by andrey-git** [comment]
Starting from HA 0.55 you can set `rgb_color` attribute of an entity and the icon will take that color.

**Comment by andrey-git** [comment]
@nalipaz did that work for you?

**Comment by nalipaz** [comment]
Sorry, I got busy. I think it helps, but I don't really have success with changing the property using custom-ui. Perhaps I was doing something wrong. I ended up using an automation.
