### ISSUE TITLE
Dimmer switches supported?

### ISSUE THREAD

**Issue by edif30** [andrey-git/home-assistant-custom-ui#49]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Latest Chrome

**CustomUI version:** 
Latest
**Home Assistant release (`hass --version`):** 
0.55
**Problem-relevant `configuration.yaml` entries:**
```yaml

```

**Problem-relevant Home Assistant log entries:**
```

```

 
**Any errors from browser Javascript console:**
```

```
Are dimmer switches even supported?  I don't see any reference to what types of devices are supported.  Reason I ask is I can only control lights.  Not switches that are dimmable.

**Comment by andrey-git** [comment]
What homeassistant platform are you looking at? Generally i think anything dimmable is considered a light.

**Comment by edif30** [comment]
I use GE zwave switches and they are configured under switch - https://home-assistant.io/components/switch/

**Comment by edif30** [comment]
I think I figured it out.  My switches are fed from mqtt bridge (ST) and I don't have the brightness topic configured.  Doing that now.
