### ISSUE TITLE
Hass.io

### ISSUE THREAD

**Issue by dannyhanes** [andrey-git/home-assistant-custom-ui#52]
Is it possible to get this working in hass.io ? Perhaps has a add-on?

**Comment by sumitrajancse** [comment]
Yes.... Its work on hass.io ... Just follow the instructions and you can have it working on hass.io

**Comment by dannyhanes** [comment]
Ah, so I ran the script and it says `In HA 0.53+ is added automatically to config panel.` however after running the script and a restart, I am not seeing it. Do I need to add something to the config?

**Comment by sumitrajancse** [comment]
Copy all the files to correct path and add the code of line as mentioned in the https://github.com/andrey-git/home-assistant-customizer/. 
After that restart the home assistant. 
After restart open the configuration , you will see the custom UI inside it.

**Comment by andrey-git** [comment]
Closing as seems there are no AIs for me here.
