### ISSUE TITLE
How to setup this with Home Assistant Docker?

### ISSUE THREAD

**Issue by joq3** [andrey-git/home-assistant-custom-ui#53]
Hi,

I'm using the latest version of Home Assistant via Docker. I have it setup so that it will update everytime there is a new release via Watchtower. A new Docker container is created, but all configs still work as they are kept locally.
Is it possible to install this on a Docker container, without loosing it everytime Home Assistant is updated and a new container is created?

Thank you!

**Comment by andrey-git** [comment]
CustomUI files are kept in the config directory, so if the update doesn't touch it - CustomUI should be safe too.

**Comment by andrey-git** [comment]
Since there seems to be no AIs for me / code issues - closing this issue.

**Comment by nardev** [comment]
But what about the paths, maybe you could add some more info in the install doc for docker?
