### ISSUE TITLE
Uncaught TypeError: Class constructor a cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Sennevds** [andrey-git/home-assistant-custom-ui#54]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Google Chrome version 62.0.3202.94

**CustomUI version:** Custom UI 20171117

**Home Assistant release (`hass --version`):** 0.58.1

**Any errors from browser Javascript console:**
```
Uncaught TypeError: Class constructor a cannot be invoked without 'new'
function e() {
                return _classCallCheck(this, e),
                _possibleConstructorReturn(this, (e.__proto__ || Object.getPrototypeOf(e)).apply(this, arguments))
            }
```
this with the tag ?latest in my url. Sliders not showing even after refresh

**Comment by andrey-git** [comment]
?latest is incompatible with my customUI right now. Support will be added in 0.59

**Comment by Sennevds** [comment]
owkey nice to know because your latest update said update for 58 i thought maybe it's for the new js frontend

**Comment by andreasnanko** [comment]
Yeah, same problem here too. It seems that the blog post is not that clear, since they mentioned that we have to update custom-ui to work with new frontend. 

So just to clarify:
custom-ui is not compatible to javascript_version: latest

@andrey-git thanks for the good work, looking forward to try the new javascript version as soon as custom-ui is ready 👍

**Comment by kylerw** [comment]
I have disabled the latest js and still getting this error.

**Comment by andrey-git** [comment]
There are several separate issues mixed here:
HA 0.58 + 20171117: Custom UI release only has es5 version, so trying `?latest` breaks customUI
HA 0.58 + hosted CustomUI 20171117 pulls 20171129 which is `latest` by default, so `?es5` doesn't work and `?latest` works.

For anyone using `customizer`: Using the latest version of customizer (20171129) should load the correct version of CustomUI for both HA 0.58.x and 0.59

Anyone not using `customizer`:
* HA 0.58 + 20171117: Only `es5` version works as was said in 0.58's release notes.
* HA 0.58 + 20171129: Only a single version (es5/latest) can be loaded. Instructions were unclear about it. Updated.
* HA 0.59 + 20171129: Both versions (es5/latest) can be loaded. See instructions.

**Comment by hvbhome** [comment]
well, i missed this... installed the latest update on my 59.1 Hassio and all cards are empty... on Mac safari and chrome. iOS App shows fine.

reading the above, im not sure what to do? my logs showed an error on the extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html line in my frontend.yaml so I've taken that out. How can we fix this please?

Cheers,
Marius

**Comment by andrey-git** [comment]
So far there was no report that looks like something needs fixing in the code. In the previous comment I listed the supported combinations. They are also listed here https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/activating.md

I'm closing this issue. If someone has an error not covered here - please open a new one with full details.

**Comment by hvbhome** [comment]
Sorry, my mistake, thought i was on the latest Hassio, but it was 0.58.1 and not .59 yet.
Cheers,
and thanks,
Marius


Op 2 dec. 2017, om 20:43 heeft Andrey <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


So far there was no report that looks like something needs fixing in the code. In the previous comment I listed the supported combinations. They are also listed here https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/activating.md

I'm closing this issue. If someone has an error not covered here - please open a new one with full details.
