### ISSUE TITLE
Rename devices globally

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#57]
Hello,

I'm struggling a bit with services.yaml / set-device name - If I understand the feature correctly I can set a cryptic device name, which is provided i.e. from my Xiaomi hub to a custom-name right?

In example I want change `binary_sensor.door_window_sensor_158d0001c034e1` to `binary_sensor.climate_wc_windowshutter` - How can I do that?

Thanks in Advance!

**Comment by andrey-git** [comment]
I don't understand the question.

You can't change entity IDs. You can set a friendly_name: https://home-assistant.io/docs/configuration/customizing-devices/

**Comment by tringler** [comment]
Ok - I don't understand what I can do with that feature: https://github.com/andrey-git/home-assistant-custom-ui/blob/master/README.md#customizer-component and how services.yaml in the customizer folder ist maybe connected to IT.

**Comment by andrey-git** [comment]
Customizer adds a service `set_attribute` that allows you to customize some attribute programatically (and not by editing `customize.yaml` file.

For example you can call
`customizer.set_attribute({"entity_id": "light.patio", "attribute": "friendly_name", "value": "My Light"})` to change the light *name* (not the *id*)

**Comment by tringler** [comment]
Ah Ok! It is somewhere explained in the project documentation?

**Comment by andrey-git** [comment]
I have added this example to customizer README
