### ISSUE TITLE
cheered too soon: updated causes empty Cards on iPhone

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#58]
---- update-edit---

I’ve reinstated the previous version (both html and gz) once more, and luckily, now i can see the content on the cards again…
must be something in the new version then ?

--------

![schermafbeelding 2017-12-03 om 11 20 56](https://user-images.githubusercontent.com/33354141/33524417-4e7f1cfa-d81d-11e7-8c88-cb9a2c92a541.jpg)
![20171203_102215000_ios](https://user-images.githubusercontent.com/33354141/33524432-aad5242c-d81d-11e7-81e4-0135495fe597.png)

cheered too soon apparently: checked on my iPhone, and now I’ve got all empty cards in the App and Browsers (Safari and Chrome) !!??

before the update to the latest custom ui, all was well.
updated, including the es5.html broke my 0.58.1 Hassio setup on the computer, but not on the iPhone. (should have read the instructions better, i know, sorry)

restoring the previous version of custom ui restored computer setup, and iPhone was fine.
updated to latest custom ui, without the es5.html this time, gave a fine computer setup, unfortunately now my iPhone is behaving strangely. All is there, but with empty cards…
No errors in the logs pointing to this at all. What to do please?

Ive refreshed many times, both on Mac and iPhone, restarted HomeAssistant, rebooted Hassio, and even uninstalled en reinstalled the app.

please see this post on the Hassio forum: https://community.home-assistant.io/t/latest-custom-ui-renders-empty-cards/34416/2

**Comment by tscibilia** [comment]
I'm getting the empty cards on my phone and the web browser.

**Comment by hvbhome** [comment]
I m good now , latest of everything, and both iPhone and Mac on safari and chrome are fine.

Do seem to miss a specific card but think that is related to home made settings .... will debug in the weekend ;-)

**Comment by andrey-git** [comment]
Closing as seems there are no reproducible issues left.
