### ISSUE TITLE
Request: Group specific entity name

### ISSUE THREAD

**Issue by randellhodges** [andrey-git/home-assistant-custom-ui#6]
Would it be possible to add something like this? Maybe not exactly the same, but some way to allow me to override the name of an entity. Even if I had to run it across a regex or something would be fine.

https://community.home-assistant.io/t/group-specific-friendly-name/12816/6

**Comment by andrey-git** [comment]
This would require much work:
* [core] Allow custom card (as opposed to state-card which are supported now)
* Make a custom group card. Group card has lots of logic - it would be bad to just fork it.

**Comment by andrey-git** [comment]
Found an easy way to do it. Implemented :)
