### ISSUE TITLE
Empty groups after updating to 0.60

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#63]
### Checklist
- [* ] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [* ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [* ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:**  63.0.3239.108

**CustomUI version:** 20171215

**Home Assistant release (`hass --version`):** 0.60.0

**Problem-relevant `configuration.yaml` entries:**
```yaml
frontend:
#  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui-es5.html
```

**Problem-relevant Home Assistant log entries:**
```
n/a
```

**Any errors from browser Javascript console:**
```
state-card-custom-ui-dbg.html:449 Uncaught SyntaxError: Identifier 'HaConfigCustomUi' has already been declared
    at state-card-custom-ui-dbg.html:449
state-card-custom-ui-dbg.html:503 Uncaught SyntaxError: Identifier 'HaThemedSlider' has already been declared
    at state-card-custom-ui-dbg.html:503
state-card-custom-ui-dbg.html:601 Uncaught SyntaxError: Identifier 'DynamicElement' has already been declared
    at state-card-custom-ui-dbg.html:601
state-card-custom-ui-dbg.html:702 Uncaught SyntaxError: Identifier 'DynamicWithExtra' has already been declared
    at state-card-custom-ui-dbg.html:702
state-card-custom-ui-dbg.html:1103 Uncaught DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-dbg.html:1103:18
state-card-custom-ui-dbg.html:1106 Uncaught SyntaxError: Identifier 'SHOW_LAST_CHANGED_BLACKLISTED_CARDS' has already been declared
    at state-card-custom-ui-dbg.html:1106
```

Since I upgraded to 0.60 all my group state cards are empty. The known behaviour if you need to refresh with CTRL+F5. However CTRL+F5 doesn't work in that case, but if I switch to the debug custom ui file it went back working:

````
frontend:
#  javascript_version: latest
  extra_html_url:
    - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-dbg.html
```
Even with the debug custom ui I get the same JS errors, but at least my groups are not empty, so it is basically working with that.

**Comment by andrey-git** [comment]
The instructions updated for 0.59
extra_html_url is for "latest" version and extra_html_url_es5 is for es5

Are you also using customizer? If so - don't add extra_html_url/extra_html_url_es5

**Comment by tringler** [comment]
Oh OK. Went back working with you instruction. I close the issue.
