### ISSUE TITLE
Badge alignment adjustment?

### ISSUE THREAD

**Issue by finish06** [andrey-git/home-assistant-custom-ui#64]
Is it possible to change the alignment of the badges when placed in a state card?

**Comment by andrey-git** [comment]
What do you mean? Could you provide a screenshot?

**Comment by finish06** [comment]
Default left alignment
![image](https://user-images.githubusercontent.com/5663312/34177744-522f1684-e4ca-11e7-850e-756a4ece8ea5.png)

Align to center
![image](https://user-images.githubusercontent.com/5663312/34177724-39a3503a-e4ca-11e7-943d-2b80a0ea4160.png)

**Comment by andrey-git** [comment]
Added variables to theme this in 20171227
