### ISSUE TITLE
option to have array of extra data template on the slider? (instead of badges)

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#68]
HI,

really loving these custom sliders!
Ive made some extra badges on the light to show temperature and brightness. But ive only been abel to show 1 value in grey on the slider itself, just below the name:

![schermafbeelding 2017-12-26 om 10 41 26](https://user-images.githubusercontent.com/33354141/34353668-c4cb24ee-ea29-11e7-94e9-5fec36d7fa57.jpg)

**Would it be possible to show more than 1 value there**? The badges might be a bit too much, but i would  love to be able to see those values, and believe the small grey ones on the slider would be perfect.
Ive tried something like this, but it wont work obviously, showing only the brightness =B attribute:

```
light.bureau:
  extra_data_template: >-
    - if (attributes.brightness) return attributes.brightness + 'B'; return null;
    - if (attributes.color_temp) return attributes.color_temp + 'C'; return null;
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: false
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: false
    report_when_not_changed: false
  extra_badge:
    - attribute: brightness
    - attribute: color_temp
```

----- edit --------
wishlist part 2:

if we could have **more than one slider**, things would get even better. Im imagining a setup where I wouldn't have to click the light to go to the sliders and change them. Have the custom-ui allow for a multiple slider setup would not force us to do so, and have all controls needed and wanted in 1 majestic view..... 
I know, I am asking a lot, but really really hope this would be an option for the development of Custom-ui.
----- end edit -----
Cheers,
Marius

**Comment by andrey-git** [comment]
Multiple `extra_data_template` support was added in 20171227.

Multiple sliders don't scale - the line breaking code is too complex as-is.
