### ISSUE TITLE
new version 271217 causes vertical outline irregularity?

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#70]
HI,

Is this introduced with the latest update or did i miss this before : vertical alignment of entity icons and name is now not correct, (entity value on the right is ok) and seems to count on another line of text?

wrong looks: 
![schermafbeelding 2017-12-27 om 12 45 34](https://user-images.githubusercontent.com/33354141/34380761-20c1d98e-eb04-11e7-81be-953ddadc49b7.jpg)

other example:

![schermafbeelding 2017-12-27 om 12 50 18](https://user-images.githubusercontent.com/33354141/34380829-8f746464-eb04-11e7-89d3-3064741d8e67.jpg)

right looks:
![schermafbeelding 2017-12-27 om 12 47 55](https://user-images.githubusercontent.com/33354141/34380771-320e0e06-eb04-11e7-99b0-afbffdcd3b7b.jpg)

if no second line of extra data is needed, the entity name next to the icon would be better vertically aligned .

Thanks,
Marius

**Comment by andrey-git** [comment]
Thanks for the report - I pushed a fixed version yesterday (I kept the name 271217)
