### ISSUE TITLE
Horizontal outlining icon and slider a bit off

### ISSUE THREAD

**Issue by Mariusthvdb** [andrey-git/home-assistant-custom-ui#76]
![a849e35d-91bd-4e94-a434-0d19e7f43cf0](https://user-images.githubusercontent.com/33354141/34460819-36ee8bc6-ee1a-11e7-97fe-dc7218459d1d.png)

Would it be possible to outline the slider and icon a bit more horizontally outlined on the left?
Right now it seems just a bit out of control... and only when the lights are off.

When turned on they look fine I think:

![f76c2f4f-b746-43b5-9998-2a528b0f9a56](https://user-images.githubusercontent.com/33354141/34460842-15120bee-ee1b-11e7-953c-1d32cd53348a.png)

On the right side, they are always a bit off , and don’t use the same available width. Maybe there is a possibility to adjust that?

**Comment by andrey-git** [comment]
The slider component takes the whole width, however it has built-in margin.
