### ISSUE TITLE
If possible, the extra badges should retrieve their own theme

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#77]
Since this got buried in another issue I am opening its own post.
Obviously (or not?), if multiple _extra badges_  are added to an entity they all take the theme of the parent (even if they have their own theme setup). 

Would it be possible to have each badge using a different theme (retrieving its theme setup)? 

I can see that we can already click on each extra badge and retrieve their own history graph (themed). Looking through your code, it seems it can be done but I am lost it the multitude of abbreviations and interlinks. :(

One example would be the one below. One badge should be blue and the other red (different alarms.. blue under 15C and red over 75% humidity). However, the humidity badge is retrieving the temperature theme.
This:
<img width="404" alt="34455339-779d373c-ed7d-11e7-8e3f-700ab4680c45" src="https://user-images.githubusercontent.com/8059190/34455339-779d373c-ed7d-11e7-8e3f-700ab4680c4d.png">
should be something like this:
<img width="404" alt="34455339-779d373c-ed7d-11e7-8e3f-700ab4680c4d" src="https://user-images.githubusercontent.com/8059190/34495525-dcb58e60-eff5-11e7-82da-d138d14c64af.png">

If I think about it, this could also be an horizontal group with the group title on the same line, no badge title and themes per entity.
Again, thank you for your work. All the best for 2018.

**Comment by andrey-git** [comment]
Starting with CustomUI 20180112 *extra badges* that represent a *real* badge (via `entity_id`) can be context-aware customized in the usual manner.

**Comment by covrig** [comment]
Thanks!
