### ISSUE TITLE
space between badges is too large

### ISSUE THREAD

**Issue by tedstriker** [andrey-git/home-assistant-custom-ui#78]
### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [ ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Safari 11.0.2.
**CustomUI version:** Custom UI 20171227
**Home Assistant release (`hass --version`):** 0.60.0

**Problem-relevant `customize.yaml` entries:**
```yaml
sensor.example_sensor:
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: badges
```

**Problem-relevant Home Assistant log entries:**
```
none
```

**Any errors from browser Javascript console:**
```
no
```
**Problem description**
There's a div around the badges (green area in screenshot) which inserts a unneccessary space between badges.
Compare the gaps between default home-assistant badges (top row) with the gaps between custom-ui badges (lower row) in the screenshot.
<img width="279" alt="badges" src="https://user-images.githubusercontent.com/795203/34547043-880b7fba-f0f8-11e7-9911-e4a0337a4953.png">

Maybe these gaps can be removed to resemble the original badge look and feel?

**Comment by andrey-git** [comment]
Starting with CustomUI 20180112 you can change the per-entity margin via `--ha-badges-card-margin` 
which defaults to "0 -6px".

Set it to "0 -16px" to eliminate margin completely. Note that in this case the first badge would be adjacent to the card border without any padding.
