### ISSUE TITLE
not working since 0.43.x

### ISSUE THREAD

**Issue by mvillarejo** [andrey-git/home-assistant-custom-ui#8]
Hello, 
First of all, thanks for these custom controls, they worked great! I said worked because it seems that since 0.43.x they have no longer worked... any idea why?

cheers

**Comment by andrey-git** [comment]
What is not working? The control doesn't show?

**Comment by mvillarejo** [comment]
Yes, the control is not displayed.

**Comment by andrey-git** [comment]
What browser are you using?
Any errors in the browser dev console? Do you have all the custom ui files?

Everything works fine on my Chrome on Linux / Android.

**Comment by mvillarejo** [comment]
I believe the error was due to the path custom component was on. Before I was using your repo as a submodule under www/custom_ui/home-assistant-custom-ui/*.html files and it did work with no issues.  it seems it no longer works. this can be closed.
