### ISSUE TITLE
Strange error log from console

### ISSUE THREAD

**Issue by hwikene** [andrey-git/home-assistant-custom-ui#83]
Hi, 
I keep getting this errors in console: https://hastebin.com/adikalopig.php
I am using Chrome and when i try to log into Hassio, it stops at "Loading Data" 
My hassio version is 0.60.1 and i have not done anything change before it started. 

I also see get an error here "DocumentFragment is not defined, please fix og add /*global documentFragment*/"
return (root instanceof DocumentFragment) ? /** @type {ShadowRoot} */ (root).host : root;

Hope you can help me with this issue.

**Comment by andrey-git** [comment]
Could you try
```yaml
customizer:
  custon_ui: debug
```

**Comment by hwikene** [comment]
Not sure where the debug log is? 
I tried adding: 
`customizer:
  custon_ui: debug`

**Comment by andrey-git** [comment]
when you replace `hosted` with `debug` the JS error log should be much more clear.

**Comment by hwikene** [comment]
it looks like i get the same errors: https://hastebin.com/ozoqatikuw.sql

**Comment by hvbhome** [comment]
HI @andrey-git 
I use the automatic install, (don't use the customizer bit in configuration) but see several related error messages in my log (i think)

how could i enable debug logging?

in /custom_components/customizer? or should i add it in

config.yaml

under 

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  customize: !include_dir_merge_named customize # customize.yaml
  customize_glob: !include customize_glob.yaml

Thanks,
Marius

**Comment by hwikene** [comment]
If i press "refresh" many times it suddenly works. but if i close browser i need to start all over again. 
This is the console log from when its working: https://hastebin.com/erepemimum.js

I am not an expert in reading these logs. 
Hope you can see some bug or errors. 
I am using your latest files form: https://github.com/andrey-git/home-assistant-custom-ui

**Comment by thelittlefireman** [comment]
@hwikene @andrey-git 
hi,
I've got exactly the same issue : 
Chrome Browser
https://hastebin.com/baziyededa.pas

**Comment by thelittlefireman** [comment]
if i comment  extra_html_url_es5:
`#    - /local/custom_ui/state-card-custom-ui-es5.html`
it works perfectly
 ```
 extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-tiles.html
  extra_html_url_es5:
#    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-tiles.html
```

**Comment by andrey-git** [comment]
I pushed 20180117 that should fix this.
