### ISSUE TITLE
Front end doesn't load with HA 0.61

### ISSUE THREAD

**Issue by edif30** [andrey-git/home-assistant-custom-ui#84]
Prior to 0.61 I was running customui from Dec 3.  After upgrading to 0.61 I did not notice any issues.  A day later I noticed that some of my sensor values were missing in the front end.  I went ahead and updated custom ui via the update.sh script.  After that, I cannot load HA via internal IP or external dns/IP.  The screen just hangs with Loading Data.  I reverted customui to the dec3 version and I can load the internal page fine (with missing sensor values again).  External only works if I do the trick of opening developer tools and ctrl+refresh.

Is there an update coming?  This seems directly related to customui and the 0.61 version.

**Comment by bhaap** [comment]
Same issue here.

**Comment by bhaap** [comment]
Reverting to 2017-12-27 worked for me. No sensors missing

**Comment by hvbhome** [comment]
+1
hang on loading Data. Still on 0.60.1, didn't update yet...did update to latest custom version VERSION:"20180114 though config shows 20171215..?

![schermafbeelding 2018-01-16 om 23 18 34](https://user-images.githubusercontent.com/33354141/35015189-8b66a4d0-fb13-11e7-8f56-6a1ef4307460.jpg)


Only working Macbook working having Custom-Ui related small issues.

Please update

**Comment by edif30** [comment]
@bhaap how did you revert to that specific version?  I had 1127 and just copied my backup files over.

**Comment by andrey-git** [comment]
I pushed 20180117 that should fix this.

**Comment by hvbhome** [comment]
i can confirm this solved the hanging on loading data issue!
hassio 0.60.1
custom-ui 20180117

on domain.duckdns.org, hassio.local and ip-address:port

thank you @andrey-git
