### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by mf-social** [andrey-git/home-assistant-custom-ui#85]
Don't panic, not an issue!

The customizer updater - once run the first time, is there ever a possibility that a future run will require any user intervention, or can I run it headless?

I ask because I have a script that automatically updates HA, pulls my github config and then restarts when a new version is released, and I want to add a line to run updater.sh so I get the latest version at the same time, but if there's a possibility it might stop and ask for some user interaction obviously that won't work.

Thanks in advance,

Marc

**Comment by andrey-git** [comment]
After the first time (where it checks for directories) it can run headless.

That said sometimes there could be breaking changes that could require a config change, so there is a danger in updating without reading release notes.

**Comment by mf-social** [comment]
Yeah, basically my formula for updates is this:

Receive a notification from HA that update is available
Read the breaking changes
Make the appropriate changes to my config on github
Hit the button in HA

This then pulls the new config from github and upgrades HA, I'll just ensure that I read for any breaking changes here and alter the config accordingly before I hit the button.

Thanks for the quick reply 👍
