### ISSUE TITLE
Question related to theme per entity: 'display: none'

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#93]
Just a question. 
Would you say that adding a variable to 'display:none' is a feasible option to hide entities (theme per entity - show entity only when needed) instead of full groups (group.set_visibility)?
Thanks.

**Comment by andrey-git** [comment]
I don't quite understand - you can already hide entities using context-aware `hidden`: https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/context-aware.md#context-aware-hide

**Comment by covrig** [comment]
Indeed that is an option. I forgot a key word: template.
I am just wondering if we can hide entities dynamically with themes. Now, we can easily attach templated themes to entities. I am just wondering if we can also hide/show them with a theme template in  CustomUi. 

I am wondering if a variable attached to the `display: ` property might do the trick... or maybe it isn't enough...
--
Thanks for the fast reply and sorry for the focusing question.

**Comment by andrey-git** [comment]
You can also do this with a template:
```
customize:
  sensor.my_sensor:
    templates:
      hidden: if (state === 'off') returns true; else return false;
```
Themes are unrelated to this

**Comment by covrig** [comment]
Excellent! 
I didn't think/investigate enough.
Thanks.

**Comment by andrey-git** [comment]
To clarify: themes don't set arbitrary CSS, they set CSS variables. There is no variable to hide an arbitrary entity.

**Comment by covrig** [comment]
That I know. :) My English the problem. :)
