### ISSUE TITLE
Is this a bug in CustomUI, HASS or just my computer?

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#94]
Two things:

- Obviously the badges are crammed together. It seems now theming and the `ha-badges-card-margin` is mandatory for all state badges to fix this. 
Was the  **-6px** in the ...`t.margin="var(--ha-badges-card-margin, 0 -6px)")`... intentional?
- I see a new 16px padding in the group that wasn't there in the last CustomUI version. The background colors were reaching the margin of the group.

Thanks.

![image](https://user-images.githubusercontent.com/8059190/35481843-396a5b00-042c-11e8-83ba-e59a4d9d674b.png)

**Comment by andrey-git** [comment]
The margin used to belong to the state card. Now it belongs to the group.
The next release will fix the default margin to 0.

**Comment by covrig** [comment]
Thanks!
