### ISSUE TITLE
Unexpected line-wrap causes the unit_of_measurement to drop

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#95]
hassio 0.62.0, customui: version 20171129 
(btw not showing anymore clicking  the _I_ in the dev section)
![schermafbeelding 2018-02-01 om 08 31 23](https://user-images.githubusercontent.com/33354141/35666574-df071fac-072a-11e8-8cd4-9ef715c1f246.jpg)

both on Mac high sierra 10.13.3 and iOS 11.3 
an unwanted line-wrap causes the unit_of_measurement to drop a line while plenty of space available:

![schermafbeelding 2018-02-01 om 08 28 35](https://user-images.githubusercontent.com/33354141/35666519-ac48c2dc-072a-11e8-9cca-60ec2652e1e4.jpg)

**Comment by andrey-git** [comment]
I think this is unrelated to CustomUI
