### ISSUE TITLE
Badge blacklist seems not to work properly

### ISSUE THREAD

**Issue by andreasnanko** [andrey-git/home-assistant-custom-ui#98]
### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome 63.0.3239.132 

**CustomUI version:** Custom UI 20180126

**Home Assistant release (`hass --version`):** 0.62.1
**Problem-relevant `configuration.yaml` entries:**
```
"light.test":
  templates:
    brightness_pct: if (attributes.brightness) return Math.round(attributes.brightness / 2.55); else return null;
  extra_badge:
    attribute: brightness_pct
    unit: '%'
```
```
"light.test":
  templates:
    brightness_pct: if (attributes.brightness) return Math.round(attributes.brightness / 2.55); else return 0;
  extra_badge:
    attribute: brightness_pct
    unit: '%'
    blacklist_states: 0
```
When I updated to latest custom-ui with updating hass from 0.60 to 0.62.1 badges started not to disappear. In the past I used return value "null" in the template to get rid of them if not needed. Now I tried to use return 0 and blacklist_states 0, but it doesn't help. Badges will always be displayed either with "null" or "0". I also tried to use "off" (the state of the light itself) since the documentation is not exactly clear to me which blacklist_state is used

**Comment by andrey-git** [comment]
I looked into it.
* There is a bug with blacklisting falsy values like 0. Will be fixed in the next release.
* The 'null' value was returned literally.

So starting with the next version either of your two configs should work.
Meanwhile you can either return `undefined` instead of `null` or cast values to string and then blacklist `'0'`:
```
"light.test":
  templates:
    brightness_pct: if (attributes.brightness) return ''+Math.round(attributes.brightness / 2.55); else return '0';
  extra_badge:
    attribute: brightness_pct
    unit: '%'
    blacklist_states: '0'
```
