### ISSUE TITLE
Context-aware friendly_name for cameras

### ISSUE THREAD

**Issue by jncanches** [andrey-git/home-assistant-custom-ui#99]
Hi, thanks for your great dev ! I really enjoy it !

I found that context-aware friendly-name does not work for cameras object in a specific group.
The displayed name (the one at the bottom of the thumbnail) is always the "default" friendly name.

```javascript
camera.living_room:
  friendly_name: Living room camera
    group:
      group.living_room_camera:
        friendly_name: Live
```

In this example, "Live" is never used, even if "camera.living_room" is displayed in "group.living_room_camera" group.

**Comment by randellhodges** [comment]
You check your spacing? 
I think group: should be even with friendly_name. Not sure if that is the cause or not.

**Comment by andrey-git** [comment]
Cameras are not displayed as state-cards, they are full-cards as as such don't enjoy from state-card-only features.
